### ISSUE TITLE
Because peek_and_pop >=1.0.2+1 depends on bloc ^2.0.0 which depends on rxdart ^0.22.0, peek_and_pop >=1.0.2+1 requires rxdart ^0.22.0.

### ISSUE THREAD

**Issue by MATTYGILO** [aliyigitbireroglu/flutter-peek-and-pop#6]
Because peek_and_pop >=1.0.2+1 depends on bloc ^2.0.0 which depends on rxdart ^0.22.0, peek_and_pop >=1.0.2+1 requires rxdart ^0.22.0.

Clash, so update the package so that it requires ^0.23.1

**Comment by aliyigitbireroglu** [comment]
Unfortunately at the moment this package is semi-discontinued. The latest Flutter updates changed way too much of the original source code which created many problems. I need some time to solve those issues but I don't think it will be soon.

Edit: Most importantly, for some reason I am unable to attach Flutter through IntelliJ to an actual iOS device which makes debugging very difficult. If anyone has any suggestions about this, I would be glad to know.

**Comment by msxenon** [comment]
Because peek_and_pop >=1.0.2+1 depends on bloc ^2.0.0 and flutter_bloc 4.0.0 depends on bloc ^4.0.0, peek_and_pop >=1.0.2+1 is incompatible with flutter_bloc 4.0.0.
And because no versions of flutter_bloc match >4.0.0 <5.0.0, peek_and_pop >=1.0.2+1 is incompatible with flutter_bloc ^4.0.0.
So, because fota depends on both flutter_bloc ^4.0.0 and peek_and_pop ^1.0.3, version solving failed.
pub get failed (1; So, because fota depends on both flutter_bloc ^4.0.0 and peek_and_pop ^1.0.3, version solving failed.)

same here, i wish u will have more time to fix this small issue
--about your iOS just update everything to latest version and it will work

**Comment by aliyigitbireroglu** [comment]
Again, unfortunately, the issues are actually more than that. The Flutter updates made after I released this package caused major changes to gesture detections and how they are handled. I can of course fix them but another problem that happened after those updates is that I can no longer run an app from the IDE on an actual iOS device with debugging and hot reload functionalities. If anyone can help me about how to solve this last part, I can fix the package easily.

**Comment by aliyigitbireroglu** [comment]
Moved to [this issue](https://github.com/aliyigitbireroglu/flutter-peek-and-pop/issues/8) and closed.
